//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FM.Server.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Login
    {
        public System.Guid LoginID { get; set; }
        public Nullable<System.Guid> DeptID { get; set; }
        public Nullable<System.Guid> StaffID { get; set; }
        public Nullable<System.Guid> DutyID { get; set; }
        public Nullable<long> StatusValue { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<bool> IsSuper { get; set; }
        public string DeviceID { get; set; }
        public Nullable<bool> IsOnline { get; set; }
    }
}
