//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ber.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTMOrder
    {
        public int id { get; set; }
        public decimal max { get; set; }
        public decimal min { get; set; }
        public decimal sum { get; set; }
        public decimal volume { get; set; }
        public string data { get; set; }
    }
}
